# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import djorm_pgfulltext.fields
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormInputLookupFact',
            fields=[
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'form_input_lookup_fact',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='FormInputLookupOb',
            fields=[
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('form', models.CharField(max_length=255)),
                ('inpt', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'form_input_lookup_ob',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GenotypeObLg',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('genotypeobserved', models.CharField(default=None, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
                'db_table': 'api_genotypeob_lg',
                'managed': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BioSample',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('typ', models.CharField(max_length=256)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BioSequence',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('typ', models.CharField(max_length=256)),
                ('string', models.TextField()),
                ('topology', models.CharField(max_length=32)),
                ('length', models.IntegerField()),
                ('url', models.CharField(max_length=2048)),
                ('comment', models.CharField(max_length=2048)),
                ('gi', models.IntegerField()),
                ('fnindex_accession', models.CharField(max_length=2048)),
                ('fnindex_id', models.CharField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='BioSubject',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('subjectname', models.CharField(max_length=255)),
                ('subjectspeciesname', models.CharField(max_length=1024)),
                ('subjecttaxon', models.IntegerField(default=None, null=True)),
                ('strain', models.CharField(default=None, max_length=1024, null=True)),
                ('subjectdescription', models.TextField(default=b'')),
                ('dob', models.DateField(default=None, null=True)),
                ('sex', models.CharField(default=None, max_length=1, null=True)),
                ('cohort', models.CharField(default=None, max_length=10, null=True)),
                ('changed', models.BooleanField(default=False)),
                ('comment', models.CharField(default=None, max_length=1024, null=True)),
                ('do_ignore', models.BooleanField(default=False)),
                ('centre', models.CharField(default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=1024)),
                ('typ', models.CharField(default=b'None', max_length=256, null=True)),
                ('supplier', models.CharField(default=b'None', max_length=2048, null=True)),
                ('physicalsourceuri', models.CharField(max_length=2048, null=True)),
                ('supplieddate', models.DateField(auto_now_add=True)),
                ('comment', models.TextField(default=b'none', null=True)),
                ('numberoffiles', models.IntegerField(default=1, null=True)),
                ('uploadsourceuri', models.CharField(default=b'', max_length=2048, null=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='EpigeneticsOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('island', models.CharField(default=b'CpG_unkown', max_length=255)),
                ('methylation', models.FloatField(null=True)),
                ('assay', models.CharField(default=b'-9999', max_length=255)),
                ('diet', models.CharField(default=b'', max_length=255)),
                ('lid', models.CharField(default=b'', max_length=255)),
                ('descriptor', models.CharField(default=b'', max_length=255)),
                ('week', models.IntegerField(null=True)),
                ('biosample', models.ForeignKey(to='api.BioSample')),
                ('biosubject', models.ForeignKey(blank=True, to='api.BioSubject', null=True)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Genotype',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('typ', models.CharField(default=b'SNP', max_length=255)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='GenotypeOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('observationdate', models.DateField(null=True)),
                ('genotypeobserved', models.CharField(default=None, max_length=255, null=True)),
                ('genotypeobserved_comment', models.CharField(default=b'', max_length=1024, null=True)),
                ('finalgenotype', models.CharField(default=None, max_length=255, null=True)),
                ('finalgenotype_comment', models.CharField(default=b'', max_length=1024, null=True)),
                ('biosubject', models.ForeignKey(to='api.BioSubject')),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
                ('genotype', models.ForeignKey(to='api.Genotype')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Labresource',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('typ', models.CharField(max_length=256)),
                ('sequence', models.TextField()),
                ('seqlength', models.IntegerField()),
                ('date', models.DateField()),
                ('supplier', models.CharField(max_length=1024)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MarkerOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('kea_id', models.CharField(max_length=255, db_index=True)),
                ('ebrida_id', models.CharField(max_length=255, db_index=True)),
                ('genotype_id', models.IntegerField(default=0, null=True, blank=True)),
                ('sex', models.CharField(max_length=10, null=True, blank=True)),
                ('values', jsonfield.fields.JSONField(default=dict)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MouseHistologyOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('descriptor', models.CharField(default=b'', max_length=255)),
                ('week', models.IntegerField(default=0)),
                ('inflam_type', models.CharField(default=b'unknown', max_length=255)),
                ('sub_type', models.CharField(default=b'=unknown', max_length=255)),
                ('score', models.FloatField(default=None, null=True)),
                ('adj_score', models.FloatField(default=None, null=True)),
                ('comments', models.CharField(default=b'', max_length=1024)),
                ('biosample', models.ForeignKey(to='api.BioSample')),
                ('biosubject', models.ForeignKey(blank=True, to='api.BioSubject', null=True)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
                ('diet', models.ForeignKey(to='api.Diet', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MouseHistologyV2Ob',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('scorer', models.CharField(default=b'unknown', max_length=20)),
                ('crypt_hyperplasia', models.IntegerField(default=None, null=True)),
                ('aberrant_crypts', models.IntegerField(default=None, null=True)),
                ('crypt_injury', models.IntegerField(default=None, null=True)),
                ('crypt_loss', models.IntegerField(default=None, null=True)),
                ('goblet_cell_loss', models.IntegerField(default=None, null=True)),
                ('crypt_abscess', models.IntegerField(default=None, null=True)),
                ('lymphoid_aggregates', models.IntegerField(default=None, null=True)),
                ('submucosal_thickening', models.IntegerField(default=None, null=True)),
                ('hyperchromatic', models.IntegerField(default=None, null=True)),
                ('surface_loss', models.IntegerField(default=None, null=True)),
                ('monocytes_and_macrophages', models.IntegerField(default=None, null=True)),
                ('neutrophils', models.IntegerField(default=None, null=True)),
                ('plasma_cells_and_lymphocytes', models.IntegerField(default=None, null=True)),
                ('muscular_layer', models.IntegerField(default=None, null=True)),
                ('omental_fat', models.IntegerField(default=None, null=True)),
                ('comments', models.CharField(default=b'', max_length=1024)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MouseIntakeOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('descriptor', models.CharField(default=b'', max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('intake', models.FloatField(default=None, null=True)),
                ('comment', models.CharField(default=b'', max_length=255)),
                ('biosubject', models.ForeignKey(blank=True, to='api.BioSubject', null=True)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
                ('diet', models.ForeignKey(to='api.Diet', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MouseWeightOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('descriptor', models.CharField(default=b'', max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('weight', models.FloatField(default=None, null=True)),
                ('comment', models.CharField(default=b'', max_length=255)),
                ('biosubject', models.ForeignKey(blank=True, to='api.BioSubject', null=True)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
                ('diet', models.ForeignKey(to='api.Diet', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Ontology',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=2048)),
                ('displayurl', models.CharField(default=b'', max_length=2048, null=True)),
                ('tablename', models.CharField(max_length=128)),
                ('owner', models.CharField(default=b'core', max_length=128, null=True)),
                ('description', models.CharField(default=b'', max_length=2048, null=True)),
                ('classname', models.CharField(max_length=128)),
            ],
            options={
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrimerOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('sequence', models.CharField(max_length=255)),
                ('tail', models.CharField(max_length=255, null=True, blank=True)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
                ('primer', models.ForeignKey(to='api.Primer')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrimerTail',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='PrimerType',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ProteinGelSpotOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('fold_change', models.FloatField(null=True)),
                ('num_uniq_pep', models.IntegerField(null=True)),
                ('spot_no', models.CharField(default=b'unkown', max_length=155)),
                ('acc_num', models.CharField(max_length=255, null=True)),
                ('gene_mgi', models.CharField(max_length=255, null=True)),
                ('prot_ident', models.CharField(max_length=255, null=True)),
                ('theo_pl', models.FloatField(null=True)),
                ('sequest_p', models.FloatField(null=True)),
                ('spot', models.IntegerField(null=True)),
                ('seq_cov', models.FloatField(null=True)),
                ('theo_al', models.FloatField(null=True)),
                ('M_Gel', models.CharField(default=b'-9999', max_length=255)),
                ('descriptor', models.CharField(default=b'', max_length=255)),
                ('week', models.IntegerField(null=True)),
                ('file_name', models.CharField(default=b'', max_length=1024)),
                ('biosample', models.ForeignKey(to='api.BioSample')),
                ('biosubject', models.ForeignKey(blank=True, to='api.BioSubject', null=True)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='QuestionnaireOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('att_key', models.CharField(max_length=255)),
                ('att_value', models.CharField(default=None, max_length=4096, null=True)),
                ('att_code', models.CharField(default=None, max_length=255, null=True)),
                ('grp', models.CharField(default=b'', max_length=1024)),
                ('biosubject', models.ForeignKey(blank=True, to='api.BioSubject', null=True)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RawImport',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='RawImportOb',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('xreflsid', models.CharField(max_length=2048)),
                ('createddate', models.DateField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('group', models.CharField(default=b'NA', max_length=1024)),
                ('recordeddate', models.DateField(auto_now_add=True)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('grp', models.IntegerField(default=0)),
                ('att_key', models.CharField(max_length=255)),
                ('att_value', models.CharField(max_length=255)),
                ('datasource', models.ForeignKey(to='api.DataSource', null=True)),
                ('imp', models.ForeignKey(to='api.RawImport')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SampleMethod',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('common_name', models.CharField(max_length=255)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('wiki', models.CharField(max_length=255)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
                ('species', models.ForeignKey(to='api.Species')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Tissue',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('no', models.IntegerField(default=0)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('name', models.CharField(default=b'unknown', max_length=255)),
                ('alias', models.CharField(default=b'unknown', max_length=255)),
                ('description', models.TextField(default=b'')),
                ('obid', models.AutoField(serialize=False, primary_key=True)),
                ('xreflsid', models.CharField(max_length=255)),
                ('createddate', models.DateTimeField(auto_now_add=True)),
                ('createdby', models.CharField(max_length=255)),
                ('lastupdateddate', models.DateTimeField(auto_now=True)),
                ('lastupdatedby', models.CharField(max_length=50)),
                ('obkeywords', models.TextField()),
                ('statuscode', models.IntegerField(default=1)),
                ('search_index', djorm_pgfulltext.fields.VectorField(default=b'', serialize=False, null=True, editable=False, db_index=True)),
                ('datasource', models.ForeignKey(default=1, to='api.DataSource')),
                ('ontology', models.ForeignKey(default=1, to='api.Ontology')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='study',
            name='study_area',
            field=models.ForeignKey(to='api.StudyArea'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='study',
            name='study_group',
            field=models.ForeignKey(to='api.StudyGroup'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='rawimportob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='rawimport',
            name='study',
            field=models.ForeignKey(to='api.Study'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='questionnaireob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='proteingelspotob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='primerob',
            name='primer_type',
            field=models.ForeignKey(blank=True, to='api.PrimerType', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='primerob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mouseweightob',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mouseweightob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mouseweightob',
            name='unit',
            field=models.ForeignKey(to='api.Unit'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mouseintakeob',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mouseintakeob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mouseintakeob',
            name='unit',
            field=models.ForeignKey(to='api.Unit'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyv2ob',
            name='all_unit',
            field=models.ForeignKey(related_name='all_unit', to='api.Unit', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyv2ob',
            name='biosample',
            field=models.ForeignKey(to='api.BioSample'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyv2ob',
            name='biosubject',
            field=models.ForeignKey(blank=True, to='api.BioSubject', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyv2ob',
            name='datasource',
            field=models.ForeignKey(to='api.DataSource', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyv2ob',
            name='diet',
            field=models.ForeignKey(to='api.Diet', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyv2ob',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyv2ob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyob',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='mousehistologyob',
            name='unit',
            field=models.ForeignKey(to='api.Unit'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='markerob',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='markerob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='labresource',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='instrument',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='genotypeob',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='genotypeob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='genotype',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='gene',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='epigeneticsob',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='epigeneticsob',
            name='study',
            field=models.ForeignKey(to='api.Study', null=True),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='epigeneticsob',
            name='unit',
            field=models.ForeignKey(to='api.Unit'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='diet',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosubject',
            name='datasource',
            field=models.ForeignKey(default=1, to='api.DataSource'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosubject',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosubject',
            name='species',
            field=models.ForeignKey(to='api.Species'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosequence',
            name='datasource',
            field=models.ForeignKey(default=1, to='api.DataSource'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosequence',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosample',
            name='biosubject',
            field=models.ForeignKey(to='api.BioSubject'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosample',
            name='datasource',
            field=models.ForeignKey(default=1, to='api.DataSource'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosample',
            name='ontology',
            field=models.ForeignKey(default=1, to='api.Ontology'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='biosample',
            name='tissue',
            field=models.ForeignKey(to='api.Tissue'),
            preserve_default=True,
        ),
    ]
